name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Zip komelt-wordpress-tools to komelt-wordpress-tools.zip
        run: zip -r ${{ github.workspace }}/komelt-wordpress-tools.zip ${{ github.workspace }}/komelt-wordpress-tools
